name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy files to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.GCP_VM_USERNAME }}/car-app"

      - name: Setup and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            # Ensure docker is installed and user has permissions
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io docker-compose
            fi
            
            # Ensure user is in docker group
            if ! groups | grep -q docker; then
              sudo usermod -aG docker $USER
              # Force group update without logout
              newgrp docker
            fi
            
            # Ensure Docker is running
            sudo systemctl start docker
            sudo systemctl enable docker
            
            cd ~/car-app
            
            # Stop any running containers
            docker-compose down || true
            
            # Build and start the application
            docker-compose up --build -d
            
            # Clean up unused images
            docker system prune -f